version: "2"
services:
    #nginx
    nginx:
        image: hub.c.163.com/library/nginx:latest
        # image: nginx:latest
        ports:
            - "80:80"
            - "1443:443"
        volumes:
            - ./www/:/usr/share/nginx/html/:rw
            - ./conf/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
            - ./conf/nginx/conf.d:/etc/nginx/conf.d/:ro
            - ./log/nginx/:/var/log/nginx/:rw

    # nodejs:
    #     image: hub.c.163.com/library/node:latest
    #     volumes:
    #         - /root/node-web-server/node:/node-web-server/node

    #redis
    redis:
        image: hub.c.163.com/library/redis:latest
        # image: redis:latest
        volumes:
            - ./conf/redis.conf:/etc/redis.conf:ro
        ports:
            - "6379:6379"
        restart: always

    #mysql
    mysql:
        image: hub.c.163.com/library/mysql:latest
        # image: mysql:5.7
        # user: "1000:50"
        ports:
            - "3306:3306"
        volumes: #因为权限的问题目录挂载被忽略了
            - ./conf/mysql/conf.d/:/etc/mysql/conf.d/:ro
            # - ./data/:/var/lib/mysql/:rw
        restart: always
        environment:
            TZ: Asia/Shanghai
            MYSQL_ROOT_PASSWORD: "root" #mysql root账号的密码
            MYSQL_USER: "test"
            MYSQL_PASS: "test"
        command: --default-authentication-plugin=mysql_native_password # --default-authentication-plugin=mysql_native_password 这行代码解决无法访问的问题

    # 构建镜像，镜像项目必须在home目录
    # node-server:
    #     build:
    #         context: .
    #         dockerfile: Dockerfile
    #     image: node-server:1.0.0
    #     container_name: node-server
    #     restart: always
    #     ports:
    #         - "7001:7001"
